### YamlMime:FAQ
metadata:
  title: Troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI and Windows Server
  description: Get help to troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI and Windows Server.

title: Fix security and identity known issues and errors
summary: |
  Use this topic to help you troubleshoot and resolve security and identity-related issues in Azure Kubernetes Service on Azure Stack HCI and Windows Server.
  
sections:
  - name: Single section - ignored
    questions:
      - question: | 
          Error 'Certificate expired - Unable to connect to the server: x509'

        answer: | 
          The target cluster is not accessible when control plane certificates fail to renew. When trying to reach the cluster, the `kubectl` command errors with the following error:
          
          `certificate expired - Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-07-26T12:24:15-04:00 is after 2022-07-15T15:01:07Z`
          
          ## To reproduce
          
          1. Install AksHci.
          2. Install target cluster.
          3. Turn off cluster(vms) for more than 4 days.
          4. Turn the cluster on again.
          
          ## Expected behavior
          
          The target cluster should be unreachable. Any `kubectl` command run against the target cluster should return with an error message similar to the following:
          
          `certificate expired - Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-07-26T12:24:15-04:00 is after 2022-07-15T15:01:07Z`
          
          1. Run the following command to renew the generate certificate manually:
             `Update-AksHciClusterCertificates  -Name my-workload-cluster -fixKubeletCredentials`
          2. Generate new credentials:
             `Get-AksHciCredential -name <clustername>`
          3. Wait a few minutes, then try the `kubectl` command for the cluster to be available again.
          
          > [!NOTE]  
          > There is a known bug in AksHci version 1.0.14.x and earlier. If the control plane VM has the name pattern other than `-control-plane-`, the `Update-AksHciClusterCertificates` command may not work. You must update the certificate by logging into the control plane VM:
          >
          > 1. Find the ip address of the target cluster control plane VM.
          > 2. Issue the following command:
          >    `ssh -i (get-mocconfig).sshPrivateKey clouduser@<ip>`
          > 3. List the cert tattoo files:
          >    `sudo ls /etc/kubernetes/pki/cert-tattoo-*`
          > 4. Generate certificates using each file listed in the previous command:
          >    `sudo /usr/bin/cert-tattoo-provision CreateCertsWithAltNames <absolute-path-of-cert-tattoo-file>`
      - question: | 
          Authentication handshake failed: x509: certificate signed by unknown authority

        answer: | 
          You may see this error when deploying a new AKS cluster or adding a node pool to an existing cluster.
          
          1. Check that the user who has run the command is the same user that installed AKS on Azure Stack or Windows Server. For more information on granting access to multiple users, see [Set up multiple administrators](set-multiple-administrators.md)
          2. If the user is the same and the error persists, follow the below steps to resolve the issue:
            - Delete old management appliance certificate by removing `$env:UserProfile.wssd\kvactl\cloudconfig`
            - Run `Repair-AksHciCerts`.
            - Run `Get-AksHciCluster` to check that it's fixed
          
      - question: | 
          KMS pod fails and the KMS pod logs contain errors

        answer: | 
          Some possible symptoms of this issue are:
          
          - `kubectl get secrets` fails with an internal error.
          - `kubectl logs <kmspod-name> -n kube-system` contains errors.
          - Mounting secrets fails in volumes when you try to create pods.
          - The apiserver fails to start.
          
          Look in the KMS pod logs for errors by running the following command:
          
          `Kubectl logs <kmspod-name> -n kube-system`
          
          If the logs return an error regarding an invalid token in the management cluster KMS pod, run the following command:
          
          `Update-AksHciCertificates`
          
          If there is an error regarding an invalid token in the target cluster KMS pod, run the following command:
          
          `UpdateAksHciClusterCertificates -name <cluster-name> -fixcloudcredential `
          
      - question: | 
          Delete KVA certificate if expired after 60 days.

        answer: | 
          KVA certificate expires after 60 day if no upgrade is performed.
          
          `Update-AksHci` and any command involving `kvactl` will throw the following error.
          
          `Error: failed to get new provider: failed to create azurestackhci session: Certificate has expired: Expired`
          
          To resolve this error, delete the expired certificate file at `\kvactl\cloudconfig` and try `Update-AksHci` again on the node seeing the certificate expiry issue. You can use the following command:
          
          ```bash
          $env:UserProfile.wssd\kvactl\cloudconfig
          ```
          
          You can find a discussion about the issue at [KVA certificate needs to be deleted if KVA Certificate expired after 60 days](https://github.com/Azure/aks-hci/issues/146)
          
      - question: | 
          Special Active Directory permissions are needed for domain joined Azure Stack HCI nodes. 

        answer: | 
          Users deploying and configuring Azure Kubernetes Service on Azure Stack HCI need to have **Full Control** permission to create AD objects in the Active Directory container the server and service objects are created in. 
          
          Elevate the user's permissions.
      - question: | 
          Uninstall-AksHciAdAuth fails with the error '[Error from server (NotFound): secrets "keytab-akshci-scale-reliability" not found]'.

        answer: | 
          If [Uninstall-AksHciAdAuth](./reference/ps/./uninstall-akshciadauth.md) displays this error, you should ignore it for now as this issue will be fixed.
          
          `This issue will be fixed.`
  

additionalContent: |
  ## Next steps
  - [Troubleshooting overview](troubleshoot-overview.md)
  - [Networking issues and errors](/azure-stack/aks-hci/known-issues-networking)
  - [storage known issues](/azure-stack/aks-hci/known-issues-storage)
  
    