### YamlMime:FAQ
metadata:
  title: Troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI
  description: Get help to troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI.

title: Fix security and identity known issues and errors
summary: |
  Use this topic to help you troubleshoot and resolve security and identity-related issues in AKS on Azure Stack HCI.
  
sections:
  - name: Single section - ignored
    questions:
      - question: | 
          Delete KVA certificate if expired after 60 days

        answer: | 
          You can find a discussion about the issue at [KVA certificate needs to be deleted if KVA Certificate expired after 60 days](https://github.com/Azure/aks-hci/issues/146)
          
          KVA certificate expires after 60 day if no upgrade is performed.
          
          `Update-AksHci` and any command involving `kvactl` will throw the following error.
          
          `Error: failed to get new provider: failed to create azurestackhci session: Certificate has expired: Expired`
          
          To resolve this error, delete the expired certificate file at `\kvactl\cloudconfig` and try `Update-AksHci` again on the node seeing the certificate expiry issue. You can use the following command:
          
          ```bash
          $env:UserProfile.wssd\kvactl\cloudconfig
          ```
          
      - question: | 
          Special Active Directory permissions are needed for domain joined Azure Stack HCI nodes 

        answer: | 
          Elevate the user's permissions.
          Users deploying and configuring Azure Kubernetes Service on Azure Stack HCI need to have **Full Control** permission to create AD objects in the Active Directory container the server and service objects are created in. 
          
      - question: | 
          Uninstall-AksHciAdAuth fails with the error `[Error from server (NotFound): secrets "keytab-akshci-scale-reliability" not found]`

        answer: | 
          `This issue will be fixed.`
          If [Uninstall-AksHciAdAuth](./reference/ps/./uninstall-akshciadauth.md) displays this error, you should ignore it for now as this issue will be fixed.
          
  

additionalContent: |
  ## Next steps
  - [Troubleshooting overview](troubleshoot-overview.md)
  - [Networking issues and errors](/azure-stack/aks-hci/known-issues-networking)
  - [storage known issues](/azure-stack/aks-hci/known-issues-storage)
  
    