### YamlMime:FAQ
metadata:
  title: Troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI and Windows Server
  description: Get help to troubleshoot security and identity issues and errors in Azure Kubernetes Service on Azure Stack HCI and Windows Server.

title: Fix security and identity known issues and errors
summary: |
  Use this topic to help you troubleshoot and resolve security and identity-related issues in Azure Kubernetes Service on Azure Stack HCI and Windows Server.
  
sections:
  - name: Single section - ignored
    questions:
      - question: | 
          Authentication handshake failed: x509: certificate signed by unknown authority

        answer: | 
          You may see this error when deploying a new AKS cluster or adding a node pool to an existing cluster.
          
          1. Check that the user who has run the command is the same user that installed AKS on Azure Stack or Windows Server. For more information on granting access to multiple users, see [Set up multiple administrators](set-multiple-administrators.md)
          2. If the user is the same and the error persists, follow the below steps to resolve the issue:
            - Delete old management appliance certificate by removing `$env:UserProfile.wssd\kvactl\cloudconfig`
            - Run `Repair-AksHciCerts`.
            - Run `Get-AksHciCluster` to check that it's fixed
          
      - question: | 
          Delete KVA certificate if expired after 60 days.

        answer: | 
          KVA certificate expires after 60 day if no upgrade is performed.
          
          `Update-AksHci` and any command involving `kvactl` will throw the following error.
          
          `Error: failed to get new provider: failed to create azurestackhci session: Certificate has expired: Expired`
          
          To resolve this error, delete the expired certificate file at `\kvactl\cloudconfig` and try `Update-AksHci` again on the node seeing the certificate expiry issue. You can use the following command:
          
          ```bash
          $env:UserProfile.wssd\kvactl\cloudconfig
          ```
          
          You can find a discussion about the issue at [KVA certificate needs to be deleted if KVA Certificate expired after 60 days](https://github.com/Azure/aks-hci/issues/146)
          
      - question: | 
          Special Active Directory permissions are needed for domain joined Azure Stack HCI nodes. 

        answer: | 
          Users deploying and configuring Azure Kubernetes Service on Azure Stack HCI need to have **Full Control** permission to create AD objects in the Active Directory container the server and service objects are created in. 
          
          Elevate the user's permissions.
      - question: | 
          Uninstall-AksHciAdAuth fails with the error '[Error from server (NotFound): secrets "keytab-akshci-scale-reliability" not found]'.

        answer: | 
          If [Uninstall-AksHciAdAuth](./reference/ps/./uninstall-akshciadauth.md) displays this error, you should ignore it for now as this issue will be fixed.
          
          `This issue will be fixed.`
  

additionalContent: |
  ## Next steps
  - [Troubleshooting overview](troubleshoot-overview.md)
  - [Networking issues and errors](/azure-stack/aks-hci/known-issues-networking)
  - [storage known issues](/azure-stack/aks-hci/known-issues-storage)
  
    